export declare const db: import("@prisma/client/runtime/library").DynamicClientExtensionThis<import("@prisma/client/edge").Prisma.TypeMap<import("@prisma/client/runtime/library").InternalArgs & {
    result: {};
    model: {
        $allModels: {
            aggregate: () => <T, A>(this: T, args: import("@prisma/client/runtime/library").Exact<A, import("@prisma/client/runtime/library").Args<T, "aggregate"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T, A, "aggregate">>;
            count: () => <T_1, A_1>(this: T_1, args?: import("@prisma/client/runtime/library").Exact<A_1, import("@prisma/client/runtime/library").Args<T_1, "count"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_1, A_1, "count">>;
            findFirst: () => <T_2, A_2>(this: T_2, args?: import("@prisma/client/runtime/library").Exact<A_2, import("@prisma/client/runtime/library").Args<T_2, "findFirst"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_2, A_2, "findFirst">>;
            findFirstOrThrow: () => <T_3, A_3>(this: T_3, args?: import("@prisma/client/runtime/library").Exact<A_3, import("@prisma/client/runtime/library").Args<T_3, "findFirstOrThrow"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_3, A_3, "findFirstOrThrow">>;
            findMany: () => <T_4, A_4>(this: T_4, args?: import("@prisma/client/runtime/library").Exact<A_4, import("@prisma/client/runtime/library").Args<T_4, "findMany"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_4, A_4, "findMany">>;
            findUnique: () => <T_5, A_5>(this: T_5, args: import("@prisma/client/runtime/library").Exact<A_5, import("@prisma/client/runtime/library").Args<T_5, "findUnique"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_5, A_5, "findUnique">>;
            findUniqueOrThrow: () => <T_6, A_6>(this: T_6, args: import("@prisma/client/runtime/library").Exact<A_6, import("@prisma/client/runtime/library").Args<T_6, "findUniqueOrThrow"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_6, A_6, "findUniqueOrThrow">>;
            groupBy: () => <T_7, A_7>(this: T_7, args: import("@prisma/client/runtime/library").Exact<A_7, import("@prisma/client/runtime/library").Args<T_7, "groupBy"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_7, A_7, "groupBy">>;
        };
        org: {
            aggregate: () => <T, A>(this: T, args: import("@prisma/client/runtime/library").Exact<A, import("@prisma/client/runtime/library").Args<T, "aggregate"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T, A, "aggregate">>;
            count: () => <T_1, A_1>(this: T_1, args?: import("@prisma/client/runtime/library").Exact<A_1, import("@prisma/client/runtime/library").Args<T_1, "count"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_1, A_1, "count">>;
            findFirst: () => <T_2, A_2>(this: T_2, args?: import("@prisma/client/runtime/library").Exact<A_2, import("@prisma/client/runtime/library").Args<T_2, "findFirst"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_2, A_2, "findFirst">>;
            findFirstOrThrow: () => <T_3, A_3>(this: T_3, args?: import("@prisma/client/runtime/library").Exact<A_3, import("@prisma/client/runtime/library").Args<T_3, "findFirstOrThrow"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_3, A_3, "findFirstOrThrow">>;
            findMany: () => <T_4, A_4>(this: T_4, args?: import("@prisma/client/runtime/library").Exact<A_4, import("@prisma/client/runtime/library").Args<T_4, "findMany"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_4, A_4, "findMany">>;
            findUnique: () => <T_5, A_5>(this: T_5, args: import("@prisma/client/runtime/library").Exact<A_5, import("@prisma/client/runtime/library").Args<T_5, "findUnique"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_5, A_5, "findUnique">>;
            findUniqueOrThrow: () => <T_6, A_6>(this: T_6, args: import("@prisma/client/runtime/library").Exact<A_6, import("@prisma/client/runtime/library").Args<T_6, "findUniqueOrThrow"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_6, A_6, "findUniqueOrThrow">>;
            groupBy: () => <T_7, A_7>(this: T_7, args: import("@prisma/client/runtime/library").Exact<A_7, import("@prisma/client/runtime/library").Args<T_7, "groupBy"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_7, A_7, "groupBy">>;
        };
        user: {
            aggregate: () => <T, A>(this: T, args: import("@prisma/client/runtime/library").Exact<A, import("@prisma/client/runtime/library").Args<T, "aggregate"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T, A, "aggregate">>;
            count: () => <T_1, A_1>(this: T_1, args?: import("@prisma/client/runtime/library").Exact<A_1, import("@prisma/client/runtime/library").Args<T_1, "count"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_1, A_1, "count">>;
            findFirst: () => <T_2, A_2>(this: T_2, args?: import("@prisma/client/runtime/library").Exact<A_2, import("@prisma/client/runtime/library").Args<T_2, "findFirst"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_2, A_2, "findFirst">>;
            findFirstOrThrow: () => <T_3, A_3>(this: T_3, args?: import("@prisma/client/runtime/library").Exact<A_3, import("@prisma/client/runtime/library").Args<T_3, "findFirstOrThrow"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_3, A_3, "findFirstOrThrow">>;
            findMany: () => <T_4, A_4>(this: T_4, args?: import("@prisma/client/runtime/library").Exact<A_4, import("@prisma/client/runtime/library").Args<T_4, "findMany"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_4, A_4, "findMany">>;
            findUnique: () => <T_5, A_5>(this: T_5, args: import("@prisma/client/runtime/library").Exact<A_5, import("@prisma/client/runtime/library").Args<T_5, "findUnique"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_5, A_5, "findUnique">>;
            findUniqueOrThrow: () => <T_6, A_6>(this: T_6, args: import("@prisma/client/runtime/library").Exact<A_6, import("@prisma/client/runtime/library").Args<T_6, "findUniqueOrThrow"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_6, A_6, "findUniqueOrThrow">>;
            groupBy: () => <T_7, A_7>(this: T_7, args: import("@prisma/client/runtime/library").Exact<A_7, import("@prisma/client/runtime/library").Args<T_7, "groupBy"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_7, A_7, "groupBy">>;
        };
    };
    query: {};
    client: {};
}>, import("@prisma/client/edge").Prisma.TypeMapCb, {
    result: {};
    model: {
        $allModels: {
            aggregate: () => <T, A>(this: T, args: import("@prisma/client/runtime/library").Exact<A, import("@prisma/client/runtime/library").Args<T, "aggregate"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T, A, "aggregate">>;
            count: () => <T_1, A_1>(this: T_1, args?: import("@prisma/client/runtime/library").Exact<A_1, import("@prisma/client/runtime/library").Args<T_1, "count"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_1, A_1, "count">>;
            findFirst: () => <T_2, A_2>(this: T_2, args?: import("@prisma/client/runtime/library").Exact<A_2, import("@prisma/client/runtime/library").Args<T_2, "findFirst"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_2, A_2, "findFirst">>;
            findFirstOrThrow: () => <T_3, A_3>(this: T_3, args?: import("@prisma/client/runtime/library").Exact<A_3, import("@prisma/client/runtime/library").Args<T_3, "findFirstOrThrow"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_3, A_3, "findFirstOrThrow">>;
            findMany: () => <T_4, A_4>(this: T_4, args?: import("@prisma/client/runtime/library").Exact<A_4, import("@prisma/client/runtime/library").Args<T_4, "findMany"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_4, A_4, "findMany">>;
            findUnique: () => <T_5, A_5>(this: T_5, args: import("@prisma/client/runtime/library").Exact<A_5, import("@prisma/client/runtime/library").Args<T_5, "findUnique"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_5, A_5, "findUnique">>;
            findUniqueOrThrow: () => <T_6, A_6>(this: T_6, args: import("@prisma/client/runtime/library").Exact<A_6, import("@prisma/client/runtime/library").Args<T_6, "findUniqueOrThrow"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_6, A_6, "findUniqueOrThrow">>;
            groupBy: () => <T_7, A_7>(this: T_7, args: import("@prisma/client/runtime/library").Exact<A_7, import("@prisma/client/runtime/library").Args<T_7, "groupBy"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_7, A_7, "groupBy">>;
        };
        org: {
            aggregate: () => <T, A>(this: T, args: import("@prisma/client/runtime/library").Exact<A, import("@prisma/client/runtime/library").Args<T, "aggregate"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T, A, "aggregate">>;
            count: () => <T_1, A_1>(this: T_1, args?: import("@prisma/client/runtime/library").Exact<A_1, import("@prisma/client/runtime/library").Args<T_1, "count"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_1, A_1, "count">>;
            findFirst: () => <T_2, A_2>(this: T_2, args?: import("@prisma/client/runtime/library").Exact<A_2, import("@prisma/client/runtime/library").Args<T_2, "findFirst"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_2, A_2, "findFirst">>;
            findFirstOrThrow: () => <T_3, A_3>(this: T_3, args?: import("@prisma/client/runtime/library").Exact<A_3, import("@prisma/client/runtime/library").Args<T_3, "findFirstOrThrow"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_3, A_3, "findFirstOrThrow">>;
            findMany: () => <T_4, A_4>(this: T_4, args?: import("@prisma/client/runtime/library").Exact<A_4, import("@prisma/client/runtime/library").Args<T_4, "findMany"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_4, A_4, "findMany">>;
            findUnique: () => <T_5, A_5>(this: T_5, args: import("@prisma/client/runtime/library").Exact<A_5, import("@prisma/client/runtime/library").Args<T_5, "findUnique"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_5, A_5, "findUnique">>;
            findUniqueOrThrow: () => <T_6, A_6>(this: T_6, args: import("@prisma/client/runtime/library").Exact<A_6, import("@prisma/client/runtime/library").Args<T_6, "findUniqueOrThrow"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_6, A_6, "findUniqueOrThrow">>;
            groupBy: () => <T_7, A_7>(this: T_7, args: import("@prisma/client/runtime/library").Exact<A_7, import("@prisma/client/runtime/library").Args<T_7, "groupBy"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_7, A_7, "groupBy">>;
        };
        user: {
            aggregate: () => <T, A>(this: T, args: import("@prisma/client/runtime/library").Exact<A, import("@prisma/client/runtime/library").Args<T, "aggregate"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T, A, "aggregate">>;
            count: () => <T_1, A_1>(this: T_1, args?: import("@prisma/client/runtime/library").Exact<A_1, import("@prisma/client/runtime/library").Args<T_1, "count"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_1, A_1, "count">>;
            findFirst: () => <T_2, A_2>(this: T_2, args?: import("@prisma/client/runtime/library").Exact<A_2, import("@prisma/client/runtime/library").Args<T_2, "findFirst"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_2, A_2, "findFirst">>;
            findFirstOrThrow: () => <T_3, A_3>(this: T_3, args?: import("@prisma/client/runtime/library").Exact<A_3, import("@prisma/client/runtime/library").Args<T_3, "findFirstOrThrow"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_3, A_3, "findFirstOrThrow">>;
            findMany: () => <T_4, A_4>(this: T_4, args?: import("@prisma/client/runtime/library").Exact<A_4, import("@prisma/client/runtime/library").Args<T_4, "findMany"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_4, A_4, "findMany">>;
            findUnique: () => <T_5, A_5>(this: T_5, args: import("@prisma/client/runtime/library").Exact<A_5, import("@prisma/client/runtime/library").Args<T_5, "findUnique"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_5, A_5, "findUnique">>;
            findUniqueOrThrow: () => <T_6, A_6>(this: T_6, args: import("@prisma/client/runtime/library").Exact<A_6, import("@prisma/client/runtime/library").Args<T_6, "findUniqueOrThrow"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_6, A_6, "findUniqueOrThrow">>;
            groupBy: () => <T_7, A_7>(this: T_7, args: import("@prisma/client/runtime/library").Exact<A_7, import("@prisma/client/runtime/library").Args<T_7, "groupBy"> & import("@prisma/extension-accelerate").PrismaCacheStrategy>) => import("@prisma/extension-accelerate").AcceleratePromise<import("@prisma/client/runtime/library").Result<T_7, A_7, "groupBy">>;
        };
    };
    query: {};
    client: {};
}>;
